[package]
name = "pad"
version = "0.1.0"
authors = ["Marcel Garus <marcel.garus@gmail.com>"]
edition = "2018"

# [lib]
# name = "pad"
# path = "src/parser.rs"

[[bin]]
name = "scanner"
path = "src/main.rs"

[dependencies]
clap = "2.26.0"
