[package]
name = "semdoc_cli"
version = "0.0.1"
authors = ["Marcel Garus <marcel.garus@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2"
colored = "2"
semdoc = { path = "../engine" }
markdown_to_semdoc = { path = "../convert/markdown-to-semdoc" }
textwrap = "0.13"
terminal_size = "0.1"
