[package]
name = "semdoc"
version = "0.0.1"
authors = ["Marcel Garus <marcel.garus@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2"
colored = "2"
semdoc_engine = { path = "../engine" }
markdown_to_semdoc = { path = "../convert/markdown-to-semdoc" }
