[package]
name = "mlml_parser"
version = "0.1.0"
authors = ["Marcel Garus <marcel.garus@gmail.com>"]
edition = "2018"

# [lib]
# name = "mlml_parser"
# path = "src/parser.rs"

[[bin]]
name = "scanner"
path = "src/main.rs"
